Web/Co(mpressed)okies/web/src/app.py
from flask import Flask, g

from src.views import home, admin, user

app = Flask(__name__, instance_relative_config=True)


@app.teardown_appcontext
def close_connection(exception):
    db = getattr(g, "_database", None)

    if db is not None:
        db.close()

app.register_blueprint(home.bp, url_prefix="/")
app.register_blueprint(admin.bp, url_prefix="/administration")
app.register_blueprint(user.bp, url_prefix="/user")

Web/Co(mpressed)okies/web/src/views/admin.py
import inspect
import os

from flask import render_template, Blueprint, request

from src.middlewares.require_admin import require_admin
from src.auth.user import User

bp = Blueprint("admin", __name__)


@bp.route("/")
@require_admin
def home() -> str:
    user = User.from_b64(request.cookies.get("session").encode())
    flag1 = os.getenv(
        "FLAG1",
        "le flag devrait être ici, si tu vois ce message, ouvre un ticket",
    )

    user_code = inspect.getsource(User)
    return render_template(
        "pages/admin/index.html", user=user, flag1=flag1, user_code=user_code
    )

Web/Co(mpressed)okies/web/src/views/home.py
from flask import render_template, Blueprint


bp = Blueprint("home", __name__)


@bp.route("/")
def home() -> str:
    return render_template("pages/index.html")

Web/Co(mpressed)okies/web/src/views/user.py
import base64
import hashlib
from flask import (
    render_template,
    Blueprint,
    session,
    g,
    request,
    redirect,
    url_for,
    Response,
    make_response,
)

from src.auth.user import User
from src.middlewares.require_anonymous import require_anonymous
from src.middlewares.require_auth import require_auth
from src.db import query_db

bp = Blueprint("user", __name__)


@bp.before_app_request
def load_logged_in_user():
    if user_id := session.get("user_id") is None:
        g.user = None
    else:
        print(user_id)


@bp.route("/")
@require_auth
def home() -> str:
    user = User.from_b64(request.cookies.get("session").encode())
    return render_template("pages/user/index.html", user=user)


@bp.route("/login", methods=("GET", "POST"))
@require_anonymous
def login() -> Response | str:
    errors = {"nickname": [], "password": []}

    if request.method == "POST":
        if (
            not isinstance((nickname := request.form.get("nickname")), str)
            or not nickname.strip()
        ):
            errors["nickname"].append("Pseudo requis")

        if (
            not isinstance((password := request.form.get("password")), str)
            or not password.strip()
        ):
            errors["password"].append("Mot de passe requis")

        if not any(errors.values()):
            nickname = nickname.strip()
            password = hashlib.sha256(password.strip().encode()).hexdigest()

            if (
                user := query_db(
                    "select * from users where nickname = ? and password = ?",
                    (nickname, password),
                    one=True,
                )
            ) is not None:
                u = User(
                    nickname=user[1],
                    first_name=user[2],
                    last_name=user[3],
                    role=user[4],
                )
                sess = base64.b64encode(u.export().read())
                if not User.is_safe(sess):
                    return render_template("pages/error.html")

                response = make_response(redirect(url_for("admin.home")))
                response.set_cookie("session", sess.decode())
                return response
            else:
                errors["password"].append("Pseudo ou mot de passe invalide")

    return render_template("pages/user/login.html", errors=errors)


@bp.route("/register", methods=("GET", "POST"))
@require_anonymous
def register() -> Response | str:
    errors = {
        "first_name": [],
        "last_name": [],
        "nickname": [],
        "password": [],
    }

    if request.method == "POST":
        if (
            not isinstance((nickname := request.form.get("nickname")), str)
            or not nickname.strip()
        ):
            errors["nickname"].append("Pseudo requis")

        if (
            not isinstance((first_name := request.form.get("first_name")), str)
            or not first_name.strip()
        ):
            errors["first_name"].append("Prénom requis")

        if (
            not isinstance((last_name := request.form.get("last_name")), str)
            or not last_name.strip()
        ):
            errors["last_name"].append("Nom requis")

        if (
            not isinstance((password := request.form.get("password")), str)
            or not password.strip()
        ):
            errors["password"].append("Mot de passe requis")

        if not any(errors.values()):
            nickname = nickname.strip()

            if (
                query_db(
                    "select * from users where nickname = ?",
                    (nickname,),
                    one=True,
                )
                is None
            ):
                first_name = first_name.strip()
                last_name = last_name.strip()
                password = password.strip()

                query_db(
                    "insert into users (nickname, first_name, last_name, role, password) values (?, ?, ?, ?, ?)",
                    (
                        nickname,
                        first_name,
                        last_name,
                        "user",
                        hashlib.sha256(password.encode()).hexdigest(),
                    ),
                )
                return redirect(url_for("user.login"))
            else:
                errors["nickname"].append("Pseudo déjà utilisé ")

    return render_template("pages/user/register.html", errors=errors)


@bp.route("/logout")
def logout() -> Response:
    session.clear()
    return redirect(url_for("user.login"))

Web/Co(mpressed)okies/web/src/templates/base/base.html
<!doctype html>
<head>
    <title>{% block title %}Super Secure Website{% endblock %}</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet"
          href="{{ url_for('static', filename='css/uikit.min.css') }}">
    <script src="{{ url_for('static', filename='js/uikit.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/uikit-icons.min.js') }}"></script>
</head>
<body>
<nav class="uk-navbar-container">
    <div class="uk-container">
        <div uk-navbar>
            <div class="uk-navbar-left">
                <ul class="uk-navbar-nav">
                    <li {% if url_for(request.endpoint) == url_for('home.home') %}class="uk-active"{% endif %}>
                        <a href="{{ url_for('home.home') }}">Accueil</a>
                    </li>
                    <li {% if url_for(request.endpoint) == url_for('admin.home') %}class="uk-active"{% endif %}>
                        <a href="{{ url_for('admin.home') }}">Administration</a>
                    </li>
                </ul>
            </div>

            <div class="uk-navbar-right">
                <ul class="uk-navbar-nav">
                    <li>
                        <a href="#">Mon compte</a>
                        <div class="uk-navbar-dropdown">
                            <ul class="uk-nav uk-navbar-dropdown-nav">
                                {% if g.user %}
                                    <li {% if url_for(request.endpoint) == url_for('user.logout') %}class="uk-active"{% endif %}>
                                        <a href="{{ url_for('user.logout') }}">Se déconnecter</a>
                                    </li>
                                {% else %}
                                    <li {% if url_for(request.endpoint) == url_for('user.login') %}class="uk-active"{% endif %}>
                                        <a href="{{ url_for('user.login') }}">Se connecter</a>
                                    </li>
                                    <li {% if url_for(request.endpoint) == url_for('user.register') %}class="uk-active"{% endif %}>
                                        <a href="{{ url_for('user.register') }}">S'enregistrer</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

<div class="uk-container uk-margin-top">
    {% block content %}{% endblock %}
</div>
</body>

Web/Co(mpressed)okies/web/src/templates/pages/admin/index.html
{% extends "base/base.html" %}

{% block content %}
<div class="uk-child-width-1-1@m uk-grid-small uk-grid-match" uk-grid>
    <div>
        <div class="uk-card uk-card-default uk-card-body">
            <h3 class="uk-card-title">GG {{ user.nickname }} !</h3>
            <p>Voilà la première partie du flag: {{ flag1 }}<br>Va plus loin pour trouver la seconde 👀</p>

            <pre><code>{{ user_code }}</code></pre>
        </div>
    </div>
</div>
{% endblock %}

Web/Co(mpressed)okies/web/src/templates/pages/error.html
{% extends "base/base.html" %}

{% block content %}
    <div class="uk-card uk-card-default uk-card-body">
        Une erreur est survenue lors de la connexion, essayez un autre comptes. <br>
        Si le problème persiste, veuillez contacter le créateur sur Discord.
    </div>
{% endblock %}

Web/Co(mpressed)okies/web/src/templates/pages/index.html
{% extends "base/base.html" %}

{% block content %}
<div class="uk-child-width-1-3@m uk-grid-small uk-grid-match" uk-grid>
    <div>
        <div class="uk-card uk-card-default uk-card-body">
            <h3 class="uk-card-title">Default</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        </div>
    </div>
    <div>
        <div class="uk-card uk-card-primary uk-card-body">
            <h3 class="uk-card-title">Primary</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        </div>
    </div>
    <div>
        <div class="uk-card uk-card-secondary uk-card-body">
            <h3 class="uk-card-title">Secondary</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        </div>
    </div>
</div>
{% endblock %}

Web/Co(mpressed)okies/web/src/templates/pages/user/index.html
{% extends "base/base.html" %}

{% block content %}
<div class="uk-child-width-1-1@m uk-grid-small uk-grid-match" uk-grid>
    <div>
        <div class="uk-card uk-card-default uk-card-body">
            <h3 class="uk-card-title">Salut {{ user.nickname }} !</h3>
            <p>Le site est en construction pour les utilisateurs normaux, revenez plus tard 😉</p>
        </div>
    </div>
</div>
{% endblock %}

Web/Co(mpressed)okies/web/src/templates/pages/user/login.html
{% extends "base/base.html" %}

{% block content %}
    <div class="uk-card uk-card-default uk-card-body">
        <form method="post">
            <fieldset class="uk-fieldset">
                <legend class="uk-legend">Se connecter</legend>

                <div class="uk-margin">
                    <input required aria-label="Input"
                            {% if errors.nickname %}
                           title="{{ errors.nickname|join }}"
                           class="uk-input uk-form-danger"
                            {% else %}
                           class="uk-input"
                            {% endif %}
                           type="text" name="nickname" placeholder="Pseudo">
                </div>

                <div class="uk-margin">
                    <input required aria-label="Input"
                            {% if errors.password %}
                           title="{{ errors.password|join }}"
                           class="uk-input uk-form-danger"
                            {% else %}
                           class="uk-input"
                            {% endif %}
                           type="password" name="password" placeholder="Mot de passe">
                </div>

                <div class="uk-margin uk-align-right">
                    <button class="uk-button uk-button-default">
                        Se connecter
                    </button>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

Web/Co(mpressed)okies/web/src/templates/pages/user/register.html
{% extends "base/base.html" %}

{% block content %}
    <div class="uk-card uk-card-default uk-card-body">
        <form method="post">
            <fieldset class="uk-fieldset">
                <legend class="uk-legend">S'enregistrer</legend>

                <div class="uk-margin">
                    <div class="uk-child-width-1-2" uk-grid>
                        <div>
                            <input required type="text"
                                   name="first_name" placeholder="Prénom"
                                    {% if errors.first_name %}
                                   title="{{ errors.first_name|join }}"
                                   class="uk-input uk-form-danger"
                                    {% else %}
                                   class="uk-input"
                                    {% endif %}
                                   aria-label="Input">
                        </div>
                        <div>
                            <input required type="text"
                                   name="last_name" placeholder="Nom"
                                    {% if errors.last_name %}
                                   title="{{ errors.last_name|join }}"
                                   class="uk-input uk-form-danger"
                                    {% else %}
                                   class="uk-input"
                                    {% endif %}
                                   aria-label="Input">
                        </div>
                    </div>
                </div>

                <div class="uk-margin">
                    <input required type="text"
                           name="nickname"
                            {% if errors.nickname %}
                           title="{{ errors.nickname|join }}"
                           class="uk-input uk-form-danger"
                            {% else %}
                           class="uk-input"
                            {% endif %}
                           placeholder="Pseudo" aria-label="Input">
                </div>

                <div class="uk-margin">
                    <input required type="password"
                           name="password"
                            {% if errors.password %}
                           title="{{ errors.password|join }}"
                           class="uk-input uk-form-danger"
                            {% else %}
                           class="uk-input"
                            {% endif %}
                           placeholder="Mot de passe" aria-label="Input">
                </div>

                <div class="uk-margin uk-align-right">
                    <button class="uk-button uk-button-default">
                        S'enregistrer
                    </button>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}